Codebreaker console app
DaniilYusha/codebreaker_console pull request #1
Opened 2020-07-24 15:28 UTC by DaniilYusha

2020-07-25 20:25 UTC, Dimasfullxq requested changes
I think would be cool if you added GameAdapter or GameService class.

2020-07-25 20:25 UTC, Dimasfullxq commented on entities/console.rb
> +    @output.introduction
Imho in initialize should be only init data. Pls, move that from constructor.

2020-07-25 20:25 UTC, Dimasfullxq commented on entities/console.rb
> +  def hint
I think this method should be in something kinda GameAdapter class.
Console can work with that class. Its gonna be lit 🔥.

2020-07-26 15:59 UTC, artem247 approved these changes
I think it's very good

2020-07-26 15:59 UTC, artem247 commented on entities/console.rb
> +
I like it very much

2020-07-26 15:59 UTC, artem247 commented on modules/questioner.rb
> +
Nit: You can add i18n here if you're already using it elsewhere

2020-07-26 16:05 UTC, DaniilYusha commented on entities/console.rb
> +
Thanks) but previous reviewer doesn't agree with us :smile:

2020-07-26 16:06 UTC, DaniilYusha commented on modules/questioner.rb
> +
Good point, I think about it too

2020-07-26 22:14 UTC, DaniilYusha commented on modules/questioner.rb
> +
@artem247 Done

2020-07-27 10:04 UTC, Dimasfullxq approved these changes

2020-07-27 16:28 UTC, katiakub approved these changes
Everything is awesome!

2020-07-29 14:43 UTC, Svatok approved these changes
Please remove magic number

2020-07-29 14:43 UTC, Svatok commented on entities/console.rb
> +      puts '=' * 25
What is `25`? This is magic number?

2021-02-10 00:50 UTC, merged